language: node_js
node_js :
 - "node"
notifications:
  email:
    on_success: never
    on_failure: never
services:
 - postgresql
before_script:
  - psql -c 'CREATE DATABASE sgcgo_private_test;' -U postgres
  - psql -c "CREATE USER simaqian WITH PASSWORD 'password123';" -U postgres
  - psql -c "ALTER DATABASE sgcgo_private_test OWNER TO simaqian;" -U postgres
script:
  - jest && codecov
